name: deployer-test
on:
    pull_request: null
    push:
        branches:
            - master
    schedule:
        -
            cron: '* 23 * * 0'
jobs:
    production:
        runs-on: ubuntu-latest
        name: production deployer end-to-end test
        steps:
            -
                name: production
                id: production
                uses: mshanemc/deployer-check-javascript-action@master
